### PR TITLE
Migrate to django-crispy-forms 2.0

### PR DESCRIPTION
**Pull request by kosdmit**
This PR fixes issue https://github.com/django-crispy-forms/crispy-test-project/issues/34

Project has been updated to work with the latest versions of django-crispy-forms:

1. Standalone template packs added to INSTALLED_APPS, requirements.txt and Pipfile.
2. Removed 'uni-form' and 'bootstrap' template packs from CRISPY_ALLOWED_TEMPLATE_PACKS.
3. Django version has been updated to match the supported versions of the latest django-crispy-forms releases.

### CODE REVIEW

**Review by smithdc1 — COMMENTED** [review]
Thanks for the patch! 🎁 

I'm wondering about the `Pipfile` (and `Pipfile.lock` which would also need updating?). Personally I don't really use that, and it seems to duplicate `requirements.txt`. Maybe we should delete the two pipfiles. 

What do you think?

**Comment by carltongibson** [comment]
I'd vote +1 to reverting to just using a requirements.txt (and plain venv even). pipenv has kind of died. (Maybe that's a followup PR though 🤷‍♂️ )

**Comment by kosdmit** [comment]
I have the same opinion about the pipenv. I added a commit that removes the Pipefile and Pipefile.lock in this pull request.

**Comment by smithdc1** [comment]
@kosdmit Thank you!

**Pull request merged**
